# .github/workflows/deploy-backend.yml
name: CI/CD Backend (Render via Deploy Hook)

on:
  push:
    branches: [ "main" ]
    paths:
      - "counter-inst/backend/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

concurrency:
  group: render-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: counter-inst/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: counter-inst/backend/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Tests
        run: npm test --if-present -- --ci

      - name: Build (optionnel)
        run: npm run build --if-present

      # Déclenche le déploiement Render uniquement si tout est vert
      - name: Trigger Render Deploy
        if: ${{ success() }}
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          set -euo pipefail
          echo "Triggering Render deploy via Deploy Hook…"
          curl -fsS "$RENDER_DEPLOY_HOOK"
          echo "✅ Hook envoyé à Render."
