name: CI/CD Backend (Render via Deploy Hook)

on:
  push:
    branches: [ "main" ]
    paths:
      - "**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

concurrency:
  group: render-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .   # <- racine du repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (optionnel) debug de l'arborescence
      - name: Show tree
        run: |
          pwd
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Tests (Jest)
        env:
          NODE_ENV: test
        run: npm test -- --passWithNoTests

      - name: Trigger Render Deploy
        if: ${{ success() }}
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -fsS "$RENDER_DEPLOY_HOOK"
          echo "✅ Hook envoyé à Render."
