# .github/workflows/deploy-backend.yml
name: CI/CD Backend (Render via Deploy Hook)

on:
  push:
    branches: [ "main" ]
    paths:
      - "**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip tests?"
        required: false
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

concurrency:
  group: render-backend-${{ github.ref }}
  cancel-in-progress: true

env:
  # Par défaut on saute les tests (utile sur push). Tu peux override via "Run workflow".
  SKIP_TESTS: "true"

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (optionnel) voir l'arborescence
      - name: Show tree
        run: |
          pwd
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json  # ⚠️ nécessite un package-lock.json

      - name: Install
        run: npm ci  # ⚠️ nécessite un package-lock.json

      # Résout le flag final (input manuel > env par défaut)
      - name: Resolve flags
        id: flags
        run: |
          echo "skip=${{ env.SKIP_TESTS }}" >> "$GITHUB_OUTPUT"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "skip=${{ github.event.inputs.skip_tests }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Tests (Jest)
        if: steps.flags.outputs.skip != 'true'
        env:
          NODE_ENV: test
        run: npm test -- --passWithNoTests

      - name: Trigger Render Deploy
        if: ${{ success() }}
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -fsS "$RENDER_DEPLOY_HOOK"
          echo "✅ Hook envoyé à Render."
